services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Zurich
    volumes:
      - config:/config
      - downloads:/downloads
    ports:
      - 8300:8000
      - 9666:9666
    restart: unless-stopped
    networks:
      - containers

networks:
  containers:
    external: true

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=4"
      device: ":/Docker/pyload/config"
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=4"
      device: ":/Docker/pyload/downloads"