services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - home-assistant-config:/config
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home-assistant.rule=Host(`home-assistant.monphi.ch`)"
      - "traefik.http.routers.home-assistant.middlewares=https-redirect@file"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  home-assistant-config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/home-assistant/config"
