services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        container_name: speedtest-tracker-sunrise
        ports:
            - 8088:80
        environment:
            - DB_CONNECTION=sqlite
            - APP_KEY=${APP_KEY}
            - APP_TIMEZONE=Europe/Zurich
            - PUBLIC_DASHBOARD=true
            - SPEEDTEST_SCHEDULE=0 */2 * * *
        volumes:
            - config:/config
        restart: unless-stopped
        networks:
          - containers

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10"
      device: ":/var/nfs/shared/Docker/speedtest-tracker/config"

networks:
  containers:
    external: true
