services:
  paperless-ai:
    image: clusterzx/paperless-ai:latest
    container_name: paperless-ai
    user: "1004:988"
    environment:
      HOME: /app/data
      PM2_HOME: /app/data/.pm2
      NLTK_DATA: /app/data/nltk_data
    tmpfs:
      - /app/logs
      - /app/data/.pm2
      - /app/data/nltk_data
    volumes:
      - data:/app/data
    ports:
      - 8400:3000
    restart: unless-stopped
    networks:
      - containers

networks:
  containers:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/paperless-ai/data"