services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - MYJDOWNLOADER_EMAIL=${MYJDOWNLOADER_EMAIL}
      - MYJDOWNLOADER_PASSWORD=${MYJDOWNLOADER_PASSWORD}
      - MYJDOWNLOADER_DEVICE_NAME=docker
      - JDOWNLOADER_HEADLESS=1
    volumes:
      - config:/config
      - downloads:/output
    networks:
      - containers
    restart: unless-stopped

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3"
      device: ":/var/nfs/shared/Docker/jdownloader/config"
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3"
      device: ":/volume3/jdownloader"

networks:
  containers:
    external: true
