services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 0:0
    ports:
      - "8096:8096/tcp"
    volumes:
      - config:/config
      - cache:/cache
      - movies:/movies
      - shows:/shows
    restart: 'unless-stopped'
    networks:
      - containers
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,resvport"
      device: ":/var/nfs/shared/Docker/jellyfin/config"
  cache:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,resvport"
      device: ":/var/nfs/shared/Docker/jellyfin/cache"
  movies:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,resvport,ro"
      device: ":/volume3/Movies"
  shows:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,resvport,ro"
      device: ":/volume3/Shows"

networks:
  containers:
    external: true
