services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    ports:
      - "8096:8096/tcp"
    volumes:
      - config:/config
      - cache:/cache
      - movies:/movies
      - shows:/shows
    restart: 'unless-stopped'
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.monphi.ch`)" 
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096" 

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/jellyfin/config"
  cache:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/jellyfin/cache"
  movies:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,ro,nfsvers=4"
      device: ":/volume3/Movies"
  shows:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,ro,nfsvers=4"
      device: ":/volume3/Shows"

networks:
  traefik:
    external: true
