services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguard-sync
    command: run --config /config/adguard-sync.yml
    volumes:
      - config:/config
    ports:
      - 8002:8080
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/adguard-sync"

networks:
  traefik:
    external: true