services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    volumes:
        - work:/opt/adguardhome/work
        - conf:/opt/adguardhome/conf
    ports:
        - 53:53/udp
        - 8000:80
        - 8001:3000
    networks:
      - containers
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  work:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/adguard/work"

  conf:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/adguard/conf"
  
networks:
  containers:
    external: true
