services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - containers
  db:
    image: docker.io/library/postgres:16
    container_name: paperless-postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - containers

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      #- ./consume:/usr/src/paperless/consume
      - consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 0
      USERMAP_GID: 0
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_TIME_ZONE: Europe/Zurich
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_URL: https://paperless.monphi.ch
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_CONSUMER_POLLING_DELAY: 10
    networks:
      - containers

networks:
  containers:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/paperless/data"
  media:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/paperless/media"
  pgdata:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/paperless/pgdata"
  redisdata:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/paperless/redisdata"
  consume:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/paperless/consume"