services:
  filebot:
    image: jlesage/filebot
    container_name: filebot
    ports:
      - 5802:5800
    environment:
      - USER_ID=100
      - GROUP_ID=100
      - LANG=de_DE.UTF-8
      - TZ=Europe/Berlin
      - AMC_ACTION=move
      - AMC_CONFLICT=skip
      - AMC_LANG=German
      - AMC_MOVIE_FORMAT=Filme/{n}/{n} ({y})
      - AMC_SERIES_FORMAT=Serien/{n}/Staffel {s}/{n} - {s00e00} - {t}
      - AMC_PROCESS_MUSIC=n
      - AMC_INPUT_DIR=/storage/extracted
      - AMC_OUTPUT_DIR=/storage/test
    volumes:
      - config:/config
      - downloads:/storage
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebot.rule=Host(`filebot.monphi.ch`)" 
      - "traefik.http.services.filebot.loadbalancer.server.port=5802" 

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/filebot/config"
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume3/Movies/downloads"

networks:
  traefik:
    external: true