services:
  filebot:
    image: jlesage/filebot
    container_name: filebot
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - LANG=de_DE.UTF-8
      - TZ=Europe/Berlin
      - AMC_ACTION=move
      - AMC_CONFLICT=auto
      - AMC_LANG=German
      - AMC_MOVIE_FORMAT=movies/{n} ({y})
      - AMC_SERIES_FORMAT=shows/{n}/Season {s}/{n} - {s00e00} - {t}
      - AMC_PROCESS_MUSIC=n
      - AMC_INPUT_DIR=/storage
      - AMC_OUTPUT_DIR=/
      - AMC_INTERVAL=300
      - FILEBOT_GUI=0
      - WEB_LISTENING_PORT=-1
      - VNC_LISTENING_PORT=-1
      - AMC_CUSTOM_OPTIONS=--def plex=10.0.86.25:${PLEX_TOKEN} # jellyfin=10.0.86.25:${JELLYFIN_KEY}
    volumes:
      - config:/config
      - downloads:/storage
      - shows:/shows
      - movies:/movies
    networks:
      - containers
    restart: unless-stopped

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,resvport"
      device: ":/var/nfs/shared/Docker/filebot/config"
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,resvport"
      device: ":/var/nfs/shared/Docker/pyload/downloads"
  shows:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,resvport"
      device: ":/Media/Shows"
  movies:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,resvport"
      device: ":/Media/Movies"

networks:
  containers:
    external: true
