services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguard-secondary
    restart: unless-stopped
    volumes:
        - work:/opt/adguardhome/work
        - conf:/opt/adguardhome/conf
    ports:
        - 53:53/udp
        - 8000:80
        - 8001:3000
    networks:
      - containers

volumes:
  work:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3"
      device: ":/var/nfs/shared/Docker/adguard-secondary/work"

  conf:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3"
      device: ":/var/nfs/shared/Docker/adguard-secondary/conf"

networks:
  containers:
    external: true