services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguard-secondary
    restart: unless-stopped
    volumes:
        - work:/opt/adguardhome/work
        - conf:/opt/adguardhome/conf
    ports:
        - 53:53/udp
        - 8000:80

volumes:
  work:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/adguard-secondary/work"

  conf:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/adguard-secondary/conf"