services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - config:/app/config
      # - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - containers
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.monphi.ch

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,soft,rw"
      device: ":/var/nfs/shared/Docker/homepage/config"

networks:
  containers:
    external: true
