services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        container_name: speedtest-tracker-breitband
        ports:
            - 8088:80
        environment:
            - DB_CONNECTION=sqlite
            - APP_KEY=${APP_KEY}
        volumes:
            - config:/config
        restart: unless-stopped
        networks:
          - containers

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/speedtest-tracker-breitband/config"

networks:
  containers:
    external: true
