services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    network_mode: "host"
    command: tunnel run
    # environment:
    #   - "TUNNEL_TOKEN={token}"
    