name: immich

services:
  immich-server:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - containers      

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false
    networks:
      - containers 

  redis:
    container_name: immich-redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - containers 

  database:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /data/immich/postgresql:/var/lib/postgresql/data
    restart: always
    networks:
      - containers 

volumes:
  model-cache:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/immich/model-cache:"
  upload:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/immich/upload"
    
networks:
  containers:
    external: true