services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    container_name: traefik
    command:
      --providers.file.filename=/config/traefik.yml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - config:/config
      - letsencrypt:/letsencrypt
    networks:
      - traefik
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST_IP}

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/traefik/config"
  letsencrypt:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/traefik/letsencrypt"

networks:
  traefik:
    name: traefik
