services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    container_name: traefik
    command:
      --providers.file.filename=/config/traefik_not_existing.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - config:/config
      - letsencrypt:/letsencrypt
    networks:
      - traefik
    # environment:
    #   - CLOUDFLARE_EMAIL={cloudflare_email}
    #   - CLOUDFLARE_API_KEY={cloudflare_api_key}
    extra_hosts:
      - host.docker.internal:172.24.0.1

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/traefik/config"
  letsencrypt:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/traefik/letsencrypt"

networks:
  traefik:
    name: traefik
