services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - data:/root/.ollama
    restart: unless-stopped
    networks:
      - containers

networks:
  containers:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/ollama/data"