services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        container_name: speedtest-tracker
        ports:
            - 8088:80
        environment:
            - DB_CONNECTION=sqlite
        volumes:
            - config:/config
        restart: unless-stopped
        networks:
          - traefik

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.11,nfsvers=4"
      device: ":/volume6/docker/speedtest-tracker/config"

networks:
  traefik:
    external: true
